### ISSUE TITLE
Day 8: Improved Code

### ISSUE THREAD

**Issue by ShashCode2348** [CodeMaster7000/Advent-of-Code-2022#2]
Hi,
An issue with the solutions in general I feel is that they are much longer than needs be, and could be shortened down. I have copied the code for my own solution to Day 8, so please do check it out.
Thanks.
Code:

from sys import argv
visible = 0
max_dist = 0
file = open(argv[1] if len(argv)>1 else "treeheights.txt").read().strip()
lines = [l for l in file.split("\n")]
Dir = [(0, 1), (0, -1), (1, 0), (-1, 0)]
for Y in range(len(lines)):
    for X in range(len(lines[0])):
        vis = False
        score = 1
        for (x, y) in Dir:
            dx = X
            dy = Y
            dist = 1
            br = True
            while True:
                dx += x
                dy += y
                if not (0 <= dx < len(lines[Y]) and 0 <= dy < len(lines)):
                    dist -= 1
                    break
                if int(lines[Y][X]) <= int(lines[dy][dx]):
                    br = False
                    break
                dist += 1
            score *= dist
            if br:
                vis = True
        if vis:
            visible += 1
        max_dist = max(max_dist, score)
print("P1:",visible)
print("P2:",max_dist)

**Comment by CodeMaster7000** [comment]
I will review it soon.

**Comment by CodeMaster7000** [comment]
Hi @ShashCode2348 

Thanks for submitting your code. In the future, attach it as a code embed like `this`.

Although your solution is viable, the shortening makes little to no difference. The main aim I am looking for is code readability, and both are similar in terms of that standard. I fully agree that the code should be made shorter where necessary, but that can be ignored if there is not much redundant code. Albeit, I appreciate your solution, and it would be a great idea if you incorporate it into your own solutions.

Thanks
